### ISSUE TITLE
Does not support ES6 classes

### ISSUE THREAD

**Issue by ReactiveRaven** [soundstep/infuse.js#8]
IE:

```
class Foo {
    constructor(Bar, Baz) {
    }
}

injector.mapClass("Foo", Foo);

injector.getValue("Foo");
```

Expected behaviour:

* Creates an instance of Foo with Bar and Baz injected

Actual behaviour:

throws:
```
TypeError: Cannot read property '1' of null
    at Object.infuse.getDependencies (/PATH_TO_PROJECT/node_modules/infuse.js/src/infuse.js:120:27)
```

This is caused by the regex expecting the string value of the value to start with the function. In actual fact, the above would start with `class Foo {`.

**Comment by soundstep** [comment]
Hi @ReactiveRaven, I used already infuse with babel without issues.
Can you provide a bit more information? Some code, probably some workflow information as well?
Anything that would make me able to reproduce?

**Comment by soundstep** [comment]
Until then, you might be able to use property injection instead:

```
class Foo {
    constructor() {
        this.Bar = null;
        this.Baz = null;
    }
    postConstruct() {
        console.log(this.Bar, this.Baz)
    }
}
```

**Comment by david-byng** [comment]
Hi, I'm using it in Node, ie with native class support rather than through babel transpilation. Thanks for the suggestion, unfortunately it crashes before it gets to property injection, so I can't use it. I've had to fall back on ES5 prototypal inheritance instead for now.

```
// inject_names.js
"use strict";

const infuse = require("infuse.js");
const injector = new infuse.Injector();

injector.mapValue("Bar", "bar");
injector.mapValue("Baz", "baz");

class Foo {
    constructor(Bar, Baz) {
        console.log(Bar, Baz);
    }
}

injector.mapClass("Foo");

injector.getValue("Foo");
```

```
// inject_properties.js
"use strict";

const infuse = require("infuse.js");
const injector = new infuse.Injector();

injector.mapValue("Bar", "bar");
injector.mapValue("Baz", "baz");

class Foo {
    constructor() {
        this.Bar = null;
        this.Baz = null;
    }
    postConstruct() {
        console.log(this.Bar, this.Baz);
    }
}

injector.mapClass("Foo");

injector.getValue("Foo");
```

```
node inject_names.js
node inject_properties.js
```

I'm on node v5.8.0.

**Comment by ReactiveRaven** [comment]
Hi, I'm using it in Node, ie with native class support rather than through babel transpilation. Thanks for the suggestion, unfortunately it crashes before it gets to property injection, so I can't use it. I've had to fall back on ES5 prototypal inheritance instead for now.

```
// inject_names.js
"use strict";

const infuse = require("infuse.js");
const injector = new infuse.Injector();

injector.mapValue("Bar", "bar");
injector.mapValue("Baz", "baz");

class Foo {
    constructor(Bar, Baz) {
        console.log(Bar, Baz);
    }
}

injector.mapClass("Foo");

injector.getValue("Foo");
```

```
// inject_properties.js
"use strict";

const infuse = require("infuse.js");
const injector = new infuse.Injector();

injector.mapValue("Bar", "bar");
injector.mapValue("Baz", "baz");

class Foo {
    constructor() {
        this.Bar = null;
        this.Baz = null;
    }
    postConstruct() {
        console.log(this.Bar, this.Baz);
    }
}

injector.mapClass("Foo");

injector.getValue("Foo");
```

```
node inject_names.js
node inject_properties.js
```

I'm on node v5.8.0.

(and now from the right account!)

**Comment by soundstep** [comment]
I see, I used it in node but not with ES6.
The constructor injection relies on regular expression, so that won't work with es6 type classes.
I'll investigate and keep you posted.

Based on the node.js output it shouldn't be too hard to update:

```
> Test2.toString()
'class Test2 { constructor(foo){} }'
> Test3.toString()
'function Test3(bar){}'
```

**Comment by soundstep** [comment]
Please note that I've started an ES6 version there:
https://github.com/soundstep/infuse.js/tree/es6

- Class and Function will be supported
- Arrow functions will throw an error as they can't be instantiated

More details there:
https://github.com/soundstep/infuse.js/blob/es6/labs/index.js

**Comment by soundstep** [comment]
Quick update.
I'm almost there, I just need to handle ES6 default values for arguments.
Test are there if there is anything I should be checking/testing:
https://github.com/soundstep/infuse.js/blob/es6/tests/tests.Spec.js#L1132

**Comment by soundstep** [comment]
ES6 support is done in the https://github.com/soundstep/infuse.js/tree/es6 branch, I will be merging in master soon.

**Comment by soundstep** [comment]
Version 2.0.0 has been released to support ES6.
